# Pipeline economia_digital_dw

Mismo flujo que el DAG `pipeline_economia_digital_dw`: bronze → silver → gold → analytics, más las figuras.

Requiere el contenedor `ed_dw` arriba (`docker compose up -d db`).

In [1]:
import os, sys, uuid
from datetime import datetime, timezone
from pathlib import Path

# Desde el host la base está en localhost; se define antes de importar los scripts
os.environ.setdefault("DB_URL", "postgresql+psycopg2://admin:admin123@localhost:5432/economia_digital_dw")
sys.path.insert(0, str(Path.cwd() / "src"))

import pandas as pd
from sqlalchemy import create_engine
import extractor_to_bronze, bronze_to_silver, silver_to_gold, gold_analytics, figuras

engine = create_engine(os.environ["DB_URL"])

## 1. Extracción a bronze

In [2]:
extractor_to_bronze.main()

run_id: 8570ba71-3212-4d8b-8f04-55c6ce0acc8d

     endutih 2020: descargado

     endutih 2021: descargado

     endutih 2022: descargado

     endutih 2023: descargado

     endutih 2024: descargado

OK   bronze.endutih_hogares_2020: 58,154 registros (84 columnas)

OK   bronze.endutih_usuarios_2020: 58,154 registros (226 columnas)

OK   bronze.endutih_usuarios2_2020: 58,154 registros (95 columnas)

OK   bronze.endutih_hogares_2021: 59,285 registros (84 columnas)

OK   bronze.endutih_usuarios_2021: 59,285 registros (226 columnas)

OK   bronze.endutih_usuarios2_2021: 59,285 registros (95 columnas)

OK   bronze.endutih_hogares_2022: 58,540 registros (87 columnas)

OK   bronze.endutih_usuarios_2022: 58,540 registros (226 columnas)

OK   bronze.endutih_usuarios2_2022: 58,540 registros (80 columnas)

OK   bronze.endutih_hogares_2023: 58,922 registros (102 columnas)

OK   bronze.endutih_usuarios_2023: 58,922 registros (229 columnas)

OK   bronze.endutih_usuarios2_2023: 58,922 registros (92 columnas)

OK   bronze.endutih_hogares_2024: 58,080 registros (104 columnas)

OK   bronze.endutih_usuarios_2024: 58,080 registros (231 columnas)

OK   bronze.endutih_usuarios2_2024: 58,080 registros (94 columnas)

OK   bronze.endutih_diccionario: 2,065 registros
OK   bronze.endutih_cat_entidad: 32 registros

OK   bronze.vabcoel: 43 registros

OK   bronze.pibe: 1,089 registros

OK   bronze.oecd_ict_hogares: 1,105 registros

OK   bronze.oecd_ict_individuos: 2,551 registros
Carga a bronze completada.

## 2. Bronze → silver

In [3]:
bronze_to_silver.main()

run_id: beedd19a-99e0-4ac0-9ad9-6c75618931b7

OK   silver.cat_entidad: 33 registros
OK   silver.endutih_mapeo_variables: 80 registros

OK   silver.endutih_hogar: 292,981 registros

OK   silver.endutih_persona: 292,981 registros
OK   silver.vabcoel: 228 registros
OK   silver.pib_entidad: 4,158 registros
OK   silver.oecd_ict: 3,656 registros
Carga a silver completada.

## 3. Silver → gold

In [4]:
silver_to_gold.main()

run_id: 0b7e4482-f3b6-484b-8464-3788d388b5d8

     hog_internet: estimado

     hog_computadora: estimado

     hog_internet_fija: estimado

     hog_celular: estimado

     pob_smartphone: estimado

     pob_internet: estimado

     pob_computadora: estimado

     pob_celular: estimado

     pob_redes_sociales: estimado

     pob_compra: estimado

     pob_banca: estimado

     usu_compra: estimado

     usu_vende: estimado

     usu_paga: estimado

     usu_banca: estimado

     sin_internet_recursos: estimado

     sin_internet_no_interesa: estimado

     sin_internet_no_sabe: estimado

     sin_internet_sin_proveedor: estimado

OK   gold.dim_entidad: 33 registros
OK   gold.dim_tiempo: 23 registros
OK   gold.dim_indicador: 23 registros
OK   gold.dim_pais: 45 registros
OK   gold.fact_encuesta_tic: 3,160 registros
OK   gold.fact_valor_entidad: 4,158 registros
OK   gold.fact_comercio_electronico: 228 registros
OK   gold.fact_oecd_tic: 3,656 registros
OK   gold.kpi_entidad_anio: 165 registros
OK   gold.valor_entidad_anio: 693 registros
OK   gold.comercio_electronico_anio: 12 registros
Carga a gold completada.

## 4. Analytics de gold

In [5]:
gold_analytics.main()

run_id: 933a53ac-b1a6-41e9-a9ce-7ab3be9dc16f

OK   gold.resultado_brecha: 285 registros
OK   gold.resultado_tendencia: 57 registros
OK   gold.resultado_ranking: 4,384 registros
OK   gold.resultado_correlacion: 46 registros
OK   gold.resultado_validacion_oecd: 40 registros
Análisis de gold completado.

## 5. Figuras

In [6]:
figuras.main()
sorted(p.name for p in figuras.SALIDA.glob('*.png'))

OK   outputs/figures/serie_hog_internet.png
OK   outputs/figures/serie_hog_computadora.png

OK   outputs/figures/serie_hog_internet_fija.png
OK   outputs/figures/serie_pob_internet.png

OK   outputs/figures/serie_pob_smartphone.png
OK   outputs/figures/serie_usu_compra.png

OK   outputs/figures/serie_usu_vende.png
OK   outputs/figures/serie_usu_paga.png

OK   outputs/figures/serie_usu_banca.png

OK   outputs/figures/brechas_2020.png

OK   outputs/figures/ranking_2020.png

OK   outputs/figures/brechas_2021.png

OK   outputs/figures/ranking_2021.png

OK   outputs/figures/brechas_2022.png

OK   outputs/figures/ranking_2022.png

OK   outputs/figures/brechas_2023.png

OK   outputs/figures/ranking_2023.png

OK   outputs/figures/brechas_2024.png

OK   outputs/figures/ranking_2024.png
OK   outputs/figures/valor_sector51.png

OK   outputs/figures/comercio_electronico.png
OK   outputs/figures/validacion_oecd.png

['brechas_2020.png',
 'brechas_2021.png',
 'brechas_2022.png',
 'brechas_2023.png',
 'brechas_2024.png',
 'comercio_electronico.png',
 'ranking_2020.png',
 'ranking_2021.png',
 'ranking_2022.png',
 'ranking_2023.png',
 'ranking_2024.png',
 'serie_hog_computadora.png',
 'serie_hog_internet.png',
 'serie_hog_internet_fija.png',
 'serie_pob_internet.png',
 'serie_pob_smartphone.png',
 'serie_usu_banca.png',
 'serie_usu_compra.png',
 'serie_usu_paga.png',
 'serie_usu_vende.png',
 'validacion_oecd.png',
 'valor_sector51.png']

## Un vistazo a gold

In [7]:
tablas = pd.read_sql("SELECT table_name FROM information_schema.tables WHERE table_schema = 'gold' ORDER BY 1", engine)
tablas["filas"] = [pd.read_sql(f"SELECT count(*) AS n FROM gold.{t}", engine)["n"][0] for t in tablas["table_name"]]
tablas

                   table_name  filas
0   comercio_electronico_anio     12
1                 dim_entidad     33
2               dim_indicador     23
3                    dim_pais     45
4                  dim_tiempo     23
5                     etl_log     90
6   fact_comercio_electronico    228
7           fact_encuesta_tic   3160
8               fact_oecd_tic   3656
9          fact_valor_entidad   4158
10           kpi_entidad_anio    165
11           resultado_brecha    285
12      resultado_correlacion     46
13          resultado_ranking   4384
14        resultado_tendencia     57
15  resultado_validacion_oecd     40
16         valor_entidad_anio    693

In [8]:
pd.read_sql("SELECT * FROM gold.resultado_brecha LIMIT 10", engine)

,anio,id_indicador,entidad_a,entidad_b,diferencia_pp,error_estandar,z,p_value,significativa
0,2020,hog_celular,31,27,0.540998,1.055744,0.512433,6.083482e-01,False
1,2020,hog_celular,31,00,0.620970,0.641885,0.967415,3.333364e-01,False
2,2020,hog_celular,27,00,0.079972,0.852442,0.093815,9.252558e-01,False
3,2020,hog_computadora,31,27,9.371391,1.829903,5.121251,3.035147e-07,True
4,2020,hog_computadora,31,00,-0.503496,1.153452,-0.436513,6.624649e-01,False
5,2020,hog_computadora,27,00,-9.874887,1.449477,-6.812724,9.576779e-12,True
6,2020,hog_internet,31,27,11.688718,2.141350,5.458574,4.799746e-08,True
7,2020,hog_internet,31,00,-4.699927,1.251474,-3.755514,1.729863e-04,True
8,2020,hog_internet,27,00,-16.388645,1.752338,-9.352444,8.564566e-21,True
9,2020,hog_internet_fija,31,27,14.417478,2.046482,7.045005,1.854552e-12,True